export const ALL_ORDERS_WS_CONNECTION_START = 'ALL_ORDERS_WS_CONNECTION_START';
export const ALL_ORDERS_WS_CONNECTION_SUCCESS = 'ALL_ORDERS_WS_CONNECTION_SUCCESS';
export const ALL_ORDERS_WS_CONNECTION_ERROR = 'ALL_ORDERS_WS_CONNECTION_ERROR';
export const ALL_ORDERS_WS_CONNECTION_CLOSE = 'ALL_ORDERS_WS_CONNECTION_CLOSE';
export const ALL_ORDERS_WS_CONNECTION_CLOSED = 'ALL_ORDERS_WS_CONNECTION_CLOSED';
export const ALL_ORDERS_WS_GET_ORDERS = 'ALL_ORDERS_WS_GET_ORDERS';

export const USER_ORDERS_WS_CONNECTION_START = 'USER_ORDERS_WS_CONNECTION_START';
export const USER_ORDERS_WS_CONNECTION_SUCCESS = 'USER_ORDERS_WS_CONNECTION_SUCCESS';
export const USER_ORDERS_WS_CONNECTION_ERROR = 'USER_ORDERS_WS_CONNECTION_ERROR';
export const USER_ORDERS_WS_CONNECTION_CLOSE = 'USER_ORDERS_WS_CONNECTION_CLOSE';
export const USER_ORDERS_WS_CONNECTION_CLOSED = 'USER_ORDERS_WS_CONNECTION_CLOSED';
export const USER_ORDERS_WS_GET_ORDERS = 'USER_ORDERS_WS_GET_ORDERS';

export const allOrdersWsGetOrders = () => {
  return {
    type: ALL_ORDERS_WS_GET_ORDERS
  };
};

export const userOrdersWsGetOrders = () => {
  return {
    type: USER_ORDERS_WS_GET_ORDERS
  };
};